export const GET_DATA_LOADING = 'GET_DATA_LOADING';
export const ROUTE_INFO = 'ROUTE_INFO';
export const MENU_SHOW_TYPE = 'MENU_SHOW_TYPE';
export const SELECT_MENU_INFO = 'SELECT_MENU_INFO';
export const PAGE_BUTTON_LIST = 'PAGE_BUTTON_LIST';
export const USER_INFO = 'USER_INFO';
